name: pfr
description: ПФР - Обращения

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_web_plugins:
    sdk: flutter
  #
  cupertino_icons: ^1.0.2
  #
  flex_color_scheme: ^6.1.2
  get: ^4.6.5
  flutter_dropzone: ^3.0.6
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  #
  lint: ^2.1.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
